source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'a2fa' do
	use_frameworks!
	
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireNetworkActivityIndicator', '~> 2.2'
	pod 'KeychainSwift', '~> 10.0'
    pod 'SmileLock', :path => "../"
end
